# coderd -- Primary service responsible for all things Coder!
coderd:
  # coderd.image -- Injected by Coder during release.
  image: ""
  # coderd.replicas -- The number of Kubernetes Pod replicas.
  replicas: 1
  # coderd.serviceSpec -- Specification to inject for the coderd service. See:
  # https://kubernetes.io/docs/concepts/services-networking/service/
  serviceSpec:
    # coderd.serviceSpec.type -- Set the type of Service. See:
    # https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
    type: LoadBalancer
    # coderd.serviceSpec.externalTrafficPolicy -- Set the traffic policy for the service. See:
    # https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
    externalTrafficPolicy: Local
    # coderd.serviceSpec.loadBalancerIP -- Set the external IP address of the
    # Ingress service.
    loadBalancerIP: ""
    # coderd.serviceSpec.loadBalancerSourceRanges -- Traffic through the LoadBalancer
    # will be restricted to the specified client IPs. This field will be ignored if
    # the cloud provider does not support this feature.
    loadBalancerSourceRanges: []

  # coderd.devurlsHost -- Wildcard hostname to allow matching against custom-created
  # dev URLs. Leaving as an empty string results in DevURLs being disabled.
  devurlsHost: ""

  # coderd.tls -- TLS configuration for coderd.
  # These options will override dashboard configuration.
  tls:
    # coderd.tls.hostSecretName -- The secret to use for TLS.
    hostSecretName: ""
    # coderd.tls.devurlsHostSecretName -- The secret to use for DevURL TLS.
    devurlsHostSecretName: ""
  # coderd.replica -- Deploy a replica to geodistribute access to
  # workspaces for lower latency.
  replica:
    # coderd.replica.enable -- Run coderd as a replica pointing to a primary deployment.
    # Replicas enable low-latency access to workspaces all over the world. Read more:
    # TODO: Link to docs.
    enable: false
    # coderd.replica.accessURL -- URL of the replica that clients will connect
    # to.
    # e.g. https://sydney.coder.myorg.com
    accessURL: ""
    # coderd.replica.primaryURL -- URL of the primary Coder deployment. Must be
    # accessible from the replica and clients.
    # eg. https://coder.myorg.com
    primaryURL: ""
  # coderd.securityContext -- Fields related to the container's security
  # context (as opposed to the pod).
  securityContext:
    # coderd.securityContext.readonlyRootFilesystem -- Sets the root filesystem
    # of the container to read-only. It is recommended to leave this setting enabled
    # in production.
    readOnlyRootFilesystem: true
  # coderd.resources -- Kubernetes resource specification for coderd pods.
  # To unset a value, set it to "". To unset all values, set resources to nil.
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "250m"
      memory: "512Mi"
  # coderd.builtinProviderServiceAccount -- Customize the built-in Kubernetes
  # provider service account.
  builtinProviderServiceAccount:
    # coderd.builtinProviderServiceAccount.annotations -- A KV mapping of annotations. See:
    # https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
    annotations: {}
    # coderd.builtinProviderServiceAccount.labels -- Add labels to the service account
    # used for the built-in provider.
    labels: {}
# envbox -- Required for running Docker inside containers. See requirements:
# https://coder.com/docs/coder/v1.19/admin/workspace-management/cvms
envbox:
  # envbox.image -- Injected by Coder during release.
  image: ""

# Contains fields related to the Postgres backend. If providing your own
# instance, a minimum version of Postgres 11 is required with the contrib
# package installed.
postgres:
  # postgres.host -- Host of the external PostgreSQL instance.
  host: ""
  # postgres.port -- Port of the external PostgreSQL instance.
  port: ""
  # postgres.user -- User of the external PostgreSQL instance.
  user: ""
  # postgres.database -- Name of the database that Coder will use.
  # You must create this database first.
  database: ""
  # postgres.passwordSecret -- Name of an existing secret in the
  # current namespace with the password of the PostgreSQL instance.
  # The password must be contained in the secret field `password`.
  # This should be set to an empty string if the database does not
  # require a password to connect.
  passwordSecret: ""
  # postgres.sslMode -- Provides variable levels of protection for
  # the PostgreSQL connection. For acceptable values, see:
  #  https://www.postgresql.org/docs/9.1/libpq-ssl.html
  sslMode: "require"

  # postgres.default -- Configure a built-in PostgreSQL deployment.
  default:
    # postgres.default.enable -- Deploys a PostgreSQL instance. We recommend
    # using an external PostgreSQL instance in production.
    # If true, all other values are ignored.
    enable: true
    # postgres.default.image -- Injected by Coder during release.
    image: ""
    # postgres.default.storageClassName -- Set the storageClass to store
    # the database.
    storageClassName: ""
    # postgres.default.resources -- Kubernetes resource specification for the PostgreSQL pod.
    # To unset a value, set it to "". To unset all values, set resources to nil.
    resources:
      requests:
        cpu: "250m"
        memory: "1Gi"
        # postgres.default.resources.requests.storage -- Specifies the size of the volume claim
        # for persisting the database.
        storage: "10Gi"
      limits:
        cpu: "250m"
        memory: "1Gi"

# services -- Kubernetes Service configuration that applies to Coder services. 
services:
  # services.annotations -- A KV mapping of annotations. See:
  # https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  annotations: {}
  # services.clusterDomainSuffix -- Custom domain suffix for DNS resolution in your cluster. See:
  # https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/
  clusterDomainSuffix: ".svc.cluster.local"
  # services.tolerations -- Each element is a toleration object. See:
  # https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
  tolerations: []
  # services.nodeSelector -- See:
  # https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
  # services.type -- See the following for configurable types:
  # https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: "ClusterIP"

# logging -- Configures the logging format and output of Coder.
logging:
  # logging.human -- Location to send logs that are formatted for readability.
  # Set to an empty string to disable.
  human: /dev/stderr
  # logging.stackdriver -- Location to send logs that are formatted for Google
  # Stackdriver. Set to an empty string to disable.
  stackdriver: ""
  # logging.json -- Location to send logs that are formatted as JSON.
  # Set to an empty string to disable.
  json: ""

  # logging.splunk -- Coder can send logs directly to Splunk
  # in addition to file-based output.
  splunk:
    # logging.splunk.url -- Splunk HEC collector endpoint.
    url: ""
    # logging.splunk.token -- Splunk HEC collector token.
    token: ""
    # logging.splunk_channel -- Optional. Specify the channel
    # to associate messages with.
    channel: ""

# certs -- Certificate that will be mounted inside Coder services.
certs:
  secret:
    # certs.secret.name -- Name of the secret.
    name: ""
    # certs.secret.key -- Key pointing to a certificate in the secret.
    key: ""