# Values for a small local test deployment using Kind
ingress:
  useDefault: false

coderd:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi

dashboard:
  resources:
    requests:
      cpu: 0m
      memory: 16Mi

envproxy:
  resources:
    requests:
      cpu: 0m
      memory: 16Mi

timescale:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
