---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    coder.deployment: {{ include "coder.serviceName" . }}
  name: {{ include "coder.serviceName" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
  {{- range $key, $value := fromYaml (include "movedValue" (dict "Values" .Values "Key" "services.annotations")) }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  replicas: {{ include "movedValue" (dict "Values" .Values "Key" "coderd.replicas" 1) }}
  strategy:
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "25%"
  selector:
    matchLabels:
      coder.deployment: {{ include "coder.serviceName" . }}
  template:
    metadata:
      labels:
        coder.deployment: {{ include "coder.serviceName" . }}
      annotations:
      {{- range $key, $value := fromYaml (include "movedValue" (dict "Values" .Values "Key" "services.annotations")) }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    spec:
      securityContext:
        runAsNonRoot: true
      restartPolicy: Always
      # terminationGracePeriodSeconds should be set to the upper bound for container rebuilds and creates.
      # 5 minutes
      terminationGracePeriodSeconds: 300
      {{- if not .Values.coderd.replica.enable }}
      serviceAccountName: coder
      {{- end }}
{{- include "coder.services.nodeSelector" . | indent 6 }}
{{- include "coder.serviceTolerations" . | indent 6 }}
      {{- if not .Values.coderd.replica.enable }}
      initContainers:
        - name: migrations
          image: {{ include "movedValue" (dict "Values" .Values "Key" "coderd.image") }}
          imagePullPolicy: Always
          env:
            - name: HUMAN_LOG
              value: {{ .Values.logging.human | quote }}
            - name: JSON_LOG
              value: {{ .Values.logging.json | quote }}
            - name: STACKDRIVER_LOG
              value: {{ .Values.logging.stackdriver | quote }}
            - name: SPLUNK_URL
              value: {{ .Values.logging.splunk.url | quote }}
            - name: SPLUNK_TOKEN
              value: {{ .Values.logging.splunk.token | quote }}
            - name: SPLUNK_CHANNEL
              value: {{ .Values.logging.splunk.channel | quote }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEVURL_HOST
              value: {{ include "movedValue" (dict "Values" .Values "Key" "coderd.devurlsHost") }}
            - name: VERBOSE
              value: "true"
{{- include "coder.postgres.env" . | indent 12 }}
          command:
            # Bash is needed to pass signals correctly.
            - /bin/bash
            - -c
            - |
              echo Waiting on db;
              /wait_postgres.sh --host="$DB_HOST" --port="$DB_PORT" -U "$DB_USER";
              echo Starting entrypoint.sh;
              exec /entrypoint.sh coderd migrate up
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      {{- end }}
      containers:
        - name: {{ include "coder.serviceName" . }}
          image: {{ include "movedValue" (dict "Values" .Values "Key" "coderd.image") }}
          imagePullPolicy: Always
          ports:
            - name: tcp-{{ include "coder.serviceName" . }}
              containerPort: 8080
              # This name cannot be longer than 15 chars.
              # This is exposed for TURNS.
            - name: tcp-t-{{ include "coder.serviceName" . }}
              containerPort: 5349
          securityContext:
            allowPrivilegeEscalation: false
            {{- if hasKey .Values "cemanager" }}
            readOnlyRootFilesystem: {{ merge .Values dict | dig "cemanager" "securityContext" "readOnlyRootFilesystem" true }}
            {{- else }}
            readOnlyRootFilesystem: {{ merge .Values dict | dig "coderd" "securityContext" "readOnlyRootFilesystem" true }}
            {{- end }}
          # coderd is a daemon service, no need to allocate a tty for it.
          tty: false
          env:
            - name: SKIP_MIGRATIONS
              value: "true"
            - name: ASSETS_URL
            - name: HUMAN_LOG
              value: {{ .Values.logging.human | quote }}
            - name: JSON_LOG
              value: {{ .Values.logging.json | quote }}
            - name: STACKDRIVER_LOG
              value: {{ .Values.logging.stackdriver | quote }}
              # ENVBOX_IMAGE describes the image used to provide
              # additional features to users for running applications
              # such as dockerd and kubernetes.
            - name: ENVBOX_IMAGE
              value: {{ .Values.envbox.image | quote }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: VERBOSE
              value: "true"
            {{- if not .Values.coderd.replica.enable }}
            {{- if eq (include "coder.useServiceNext" .) "false" }}
            - name: BUILT_IN_ENVPROXY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: built-in-envproxy-token
                  key: token
            {{- end }}
            {{- end }}
            {{- if .Values.coderd.replica.enable }}
            - name: CODER_REPLICA_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: coder-replica-private-key
                  key: privateKey
            - name: CODER_PRIMARY_ACCESS_URL
              value: {{ .Values.coderd.replica.primaryURL | quote }}
            - name: CODER_REPLICA_ACCESS_URL
              value: {{ .Values.coderd.replica.accessURL | quote }}
            {{- end }}
            {{- if ne (include "movedValue" (dict "Values" .Values "Key" "coderd.tls.hostSecretName")) "" }}
            - name: SSL_SERVER_CERT_FILE
              value: /etc/ssl/certs/host/tls.crt
            - name: SSL_SERVER_KEY_FILE
              value: /etc/ssl/certs/host/tls.key
            {{- end }}
{{- include "coder.environments.configMapEnv" . | indent 12 }}
{{- include "coder.postgres.env" . | indent 12 }}
          command:
            # Bash is needed to pass signals correctly.
            - /bin/bash
            - -c
            - |
              {{- if not .Values.coderd.replica.enable }}
              echo Waiting on db;
              PGSSLMODE="${DB_SSL_MODE:-prefer}" /wait_postgres.sh --host="$DB_HOST" --port="$DB_PORT" -U "$DB_USER";
              echo Starting entrypoint.sh;
              # Pass signals down to the envmanager.
              exec /entrypoint.sh coderd run
              {{- else }}
              echo Starting replica;
              # Pass signals down to the envmanager.
              exec /entrypoint.sh coderd replica
              {{- end }}
          readinessProbe:
            httpGet:
              path: /cem-healthz
              port: 8080
            initialDelaySeconds: 10
            failureThreshold: 7
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /cem-healthz
              port: 8080
            initialDelaySeconds: 10
            failureThreshold: 7
            periodSeconds: 10
{{- include "coder.resources" (fromYaml (include "movedValue" (dict "Values" .Values "Key" "coderd.resources"))) | indent 10 }}
{{- include "coder.volumeMounts" . | indent 10 }}
{{- include "coder.volumes" . | indent 6 }}
{{- if .Values.coderd.replica.enable }}
---
apiVersion: v1
kind: Secret
metadata:
  name: coder-replica-private-key
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
# Adapted from https://stackoverflow.com/a/64325744
data:
  {{- if (lookup "v1" "Secret" .Release.Namespace "coder-replica-private-key") }}
  privateKey: {{ (lookup "v1" "Secret" .Release.Namespace "coder-replica-private-key").data.privateKey }}
  {{- else }}
  privateKey: {{ genPrivateKey "ecdsa" | b64enc }}
  {{- end }}
{{- end }}
{{ if eq (include "coder.useServiceNext" .) "true" }}
---
apiVersion: v1
kind: Service
metadata:
  {{- if (lookup "v1" "Service" .Release.Namespace "ingress-nginx") }}
  name: ingress-nginx
  {{- else }}
  name: {{ include "coder.serviceName" . }}
  {{- end }}
  namespace: {{ .Release.Namespace | quote }}
spec:
{{ toYaml .Values.coderd.serviceSpec | indent 2 }}
  selector:
    coder.deployment: {{ include "coder.serviceName" . }}
  ports:
    - name: tcp-{{ include "coder.serviceName" . }}
      port: 80
      targetPort: 8080
      protocol: TCP
      appProtocol: http
    - name: tcp-{{ include "coder.serviceName" . }}-https
      port: 443
      targetPort: 8443
      protocol: TCP
      appProtocol: https
    - name: tcp-{{ include "coder.serviceName" . }}-turns
      port: 5349
      protocol: TCP
      appProtocol: turns
{{- else }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "coder.serviceName" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: {{ include "movedValue" (dict "Values" .Values "Key" "services.type") | quote}}
  selector:
    coder.deployment: {{ include "coder.serviceName" . }}
  ports:
    - name: tcp-{{ include "coder.serviceName" . }}
      port: 8080
      protocol: TCP
    - name: tcp-{{ include "coder.serviceName" . }}-https
      port: 8443
      protocol: TCP
    - name: tcp-{{ include "coder.serviceName" . }}-turns
      port: 5349
      protocol: TCP
{{- end }}