---
# The service account that the envproxy passes to cemanager on startup.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coder
  namespace: {{ .Release.Namespace | quote }}
---
# The roles the manager needs in the workspace namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coder
  namespace: {{ .Release.Namespace | quote }}
rules:
  - apiGroups:
      - "" # indicates the core API group
      - "apps"
    resources:
      # Required for workspace home volumes.
      - persistentvolumeclaims
      # Workspaces are created as pods.
      - pods
      # Required for creating registry pull secrets.
      - secrets
      # Every workspace has a service.
      - services
      # LEGACY: old workspaces may be deployments, so we need this permission to
      # recreate old workspaces as pods.
      - deployments
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups:
      - "" # indicates the core API group
    resources:
      - pods/exec
      - pods/log
      - events
      - configmaps
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - "apps"
    resources:
      # LEGACY: old workspaces may be deployments
      - deployments/scale
    verbs:
      - update
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
    # Necessary for gathering stats about an environment.
    verbs:
      - list
      - get
  - apiGroups:
      - networking.k8s.io
    resources:
      # Necessary for preventing inter-environment communication.
      - networkpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: coder
subjects:
  - kind: ServiceAccount
    name: coder
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: coder
  apiGroup: rbac.authorization.k8s.io
