---
# The service account that the envproxy passes to cemanager on startup.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coder
  namespace: {{ .Release.Namespace | quote }}
  annotations:
  {{- range $key, $value := .Values.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
  {{- range $key, $value := .Values.serviceAccount.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
---
# The roles the manager needs in the environments
# namespace in order to administer pods.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coder
  namespace: {{ . | quote }}
rules:
  - apiGroups:
      - "" # indicates the core API group
      - "apps"
    resources:
      - pods
      # Required for creating registry pull secrets.
      - secrets
      # Required for the environments' home volumes.
      - persistentvolumeclaims
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups:
      - "" # indicates the core API group
    resources:
      - pods/exec
      - pods/log
      - events
      - configmaps
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - "apps"
    verbs:
      - update
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
    # Necessary for gathering stats about an environment.
    verbs:
      - list
      - get
  - apiGroups:
      - networking.k8s.io
    resources:
      # Necessary for preventing inter-environment communication.
      - networkpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ . | quote }}
  name: coder
subjects:
  - kind: ServiceAccount
    name: coder
    namespace: {{ $.Release.Namespace | quote }}
roleRef:
  kind: Role
  name: coder
  apiGroup: rbac.authorization.k8s.io
